name: py37
dependencies:
- openssl
- pip
- python=3.7
- readline
- sqlite
- tk
- wheel
- zlib
- requests
- pip:
  - sphinx_fontawesome
  - sphinxcontrib.images
  - git+git://github.com/griffithlab/sphinxcontrib-programoutput.git#egg=sphinxcontrib-programoutput
