name: py37
dependencies:
- openssl
- pip
- python=3.7
- readline
- sqlite
- tk
- wheel
- zlib
- requests
- autoconf
- automake
- libtool
- jq
- pip:
  - sphinx_fontawesome
  - sphinxcontrib-programoutput
